version: '3.8'
services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - TZ=UTC
      - HEALTH_PORT=3000
    ports:
      - "127.0.0.1:3000:3000"  # Health check endpoint, only exposed locally
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
